# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""Built-in allreduce kernel and orchestration templates for distributed codegen.

These are emitted as raw C++ PTO-ISA files (not MLIR) because the 4-phase
symmetric allreduce pattern uses cross-rank communication primitives
(``TNOTIFY``, ``TWAIT``, ``CommRemotePtr``) that are not yet expressible in
pypto's MLIR dialect.

The templates are based on the proven implementation in:
``simpler/examples/workers/l3/allreduce_distributed/kernels/``

Usage from ``pto_backend._generate_with_distributed()``::

    from pypto.backend.allreduce_builtin import (
        emit_allreduce_chip_task,
        ALLREDUCE_COUNT,
        SCRATCH_NBYTES,
    )
    result_files.update(emit_allreduce_chip_task(output_dir, count=ALLREDUCE_COUNT))
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Default configuration — must match kernel template constants.
# ---------------------------------------------------------------------------

ALLREDUCE_COUNT = 256
DTYPE_NBYTES = 4  # float32
BUFFER_NBYTES = ALLREDUCE_COUNT * DTYPE_NBYTES
SIGNAL_TAIL_NBYTES = 16 * 4  # one int32 per rank, up to 16 ranks
SCRATCH_NBYTES = BUFFER_NBYTES + SIGNAL_TAIL_NBYTES
SCRATCH_FLOOR = 4 * 1024  # minimum window size

# ---------------------------------------------------------------------------
# Allreduce AIV kernel (4-phase symmetric, HCCL window)
# ---------------------------------------------------------------------------

_ALLREDUCE_KERNEL_CPP = """/*
 * Auto-generated allreduce kernel — 4-phase symmetric HCCL window pattern.
 * Generated by PyPTO distributed codegen (allreduce_builtin.py).
 *
 * Phase 1 (stage-in):   input → my scratch slot (HCCL window)
 * Phase 2 (barrier):    TNOTIFY every peer → TWAIT until all peers ready
 * Phase 3 (compute):    TLOAD every peer's scratch → TADD into accumulator
 * Phase 4 (stage-out):  TSTORE accumulator → output
 */

#include <cstdint>
#include <pto/pto-inst.hpp>
#include "pto/comm/comm_types.hpp"
#include "pto/comm/pto_comm_inst.hpp"
#include "platform_comm/comm_context.h"
#include "tensor.h"

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif

static constexpr size_t ALLREDUCE_COUNT = {ALLREDUCE_COUNT};
static constexpr int kMaxSupportedRanks = {MAX_RANKS};

template <typename T>
AICORE inline __gm__ T *CommRemotePtr(__gm__ CommContext *ctx, __gm__ T *localPtr, int pe) {{
    uint64_t localBase = ctx->windowsIn[ctx->rankId];
    uint64_t offset = (uint64_t)localPtr - localBase;
    return (__gm__ T *)(ctx->windowsIn[pe] + offset);
}}

extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {{
    __gm__ Tensor *input_tensor = reinterpret_cast<__gm__ Tensor *>(args[0]);
    __gm__ Tensor *output_tensor = reinterpret_cast<__gm__ Tensor *>(args[1]);
    __gm__ Tensor *scratch_tensor = reinterpret_cast<__gm__ Tensor *>(args[2]);
    int nranks = static_cast<int>(args[3]);
    __gm__ CommContext *commCtx = reinterpret_cast<__gm__ CommContext *>(args[4]);

    __gm__ float *input = reinterpret_cast<__gm__ float *>(input_tensor->buffer.addr) + input_tensor->start_offset;
    __gm__ float *output = reinterpret_cast<__gm__ float *>(output_tensor->buffer.addr) + output_tensor->start_offset;
    __gm__ float *scratch =
        reinterpret_cast<__gm__ float *>(scratch_tensor->buffer.addr) + scratch_tensor->start_offset;
    __gm__ int32_t *signal_base = reinterpret_cast<__gm__ int32_t *>(scratch + ALLREDUCE_COUNT);

    using ShapeDyn = pto::Shape<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using StrideDyn = pto::Stride<pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC, pto::DYNAMIC>;
    using Global = pto::GlobalTensor<float, ShapeDyn, StrideDyn, pto::Layout::ND>;
    using TileData = pto::Tile<pto::TileType::Vec, float, 1, ALLREDUCE_COUNT, pto::BLayout::RowMajor, -1, -1>;

    int my_rank = static_cast<int>(commCtx->rankId);

    if (nranks <= 0 || nranks > kMaxSupportedRanks) {{
        pipe_barrier(PIPE_ALL);
        return;
    }}

    ShapeDyn shape(1, 1, 1, 1, ALLREDUCE_COUNT);
    StrideDyn stride(ALLREDUCE_COUNT, ALLREDUCE_COUNT, ALLREDUCE_COUNT, ALLREDUCE_COUNT, 1);

    TileData stageTile(1, ALLREDUCE_COUNT);
    TileData accTile(1, ALLREDUCE_COUNT);
    TileData recvTile(1, ALLREDUCE_COUNT);
    TASSIGN(stageTile, 0x0);
    TASSIGN(accTile, 0x10000);
    TASSIGN(recvTile, 0x20000);

    Global inputG(input, shape, stride);
    Global scratchG(scratch, shape, stride);
    Global outputG(output, shape, stride);

    // Phase 1: stage-in
    TLOAD(stageTile, inputG);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(scratchG, stageTile);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    pipe_barrier(PIPE_ALL);

    // Phase 2: device barrier
    for (int peer = 0; peer < nranks; ++peer) {{
        if (peer == my_rank) continue;
        __gm__ int32_t *remote_signal = CommRemotePtr(commCtx, signal_base + my_rank, peer);
        pto::comm::Signal sig(remote_signal);
        pto::comm::TNOTIFY(sig, (int32_t)1, pto::comm::NotifyOp::AtomicAdd);
    }}
    for (int peer = 0; peer < nranks; ++peer) {{
        if (peer == my_rank) continue;
        pto::comm::Signal sig(signal_base + peer);
        pto::comm::TWAIT(sig, (int32_t)1, pto::comm::WaitCmp::GE);
    }}
    pipe_barrier(PIPE_ALL);

    // Phase 3: compute — sum all ranks' scratch into acc
    TLOAD(accTile, scratchG);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);

    for (int peer = 0; peer < nranks; ++peer) {{
        if (peer == my_rank) continue;
        __gm__ float *remote_scratch = CommRemotePtr(commCtx, scratch, peer);
        Global remoteG(remote_scratch, shape, stride);
        TLOAD(recvTile, remoteG);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TADD(accTile, accTile, recvTile);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    }}

    // Phase 4: stage-out
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(outputG, accTile);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);

    pipe_barrier(PIPE_ALL);
}}
"""

# ---------------------------------------------------------------------------
# Allreduce orchestration shim
# ---------------------------------------------------------------------------

_ALLREDUCE_ORCH_CPP = """/*
 * Auto-generated allreduce orchestration — forwards tensor args + scalars
 * to the 4-phase allreduce kernel.
 * Generated by PyPTO distributed codegen (allreduce_builtin.py).
 *
 * Args:
 *   tensor(0) input   INPUT           (host-backed)
 *   tensor(1) output  OUTPUT_EXISTING (host-backed)
 *   tensor(2) scratch INOUT           (HCCL window; cross-rank read/write)
 *   scalar(0) nranks
 *   scalar(1) CommContext device pointer
 */

#include <stdint.h>

#include "pto_orchestration_api.h"

extern "C" {{

__attribute__((visibility("default"))) PTO2OrchestrationConfig
allreduce_config(const ChipStorageTaskArgs &orch_args) {{
    (void)orch_args;
    return PTO2OrchestrationConfig{{
        .expected_arg_count = 5,
    }};
}}

__attribute__((visibility("default"))) void allreduce_orchestration(const ChipStorageTaskArgs &orch_args) {{
    Tensor input = from_tensor_arg(orch_args.tensor(0));
    Tensor output = from_tensor_arg(orch_args.tensor(1));
    Tensor scratch = from_tensor_arg(orch_args.tensor(2));

    Arg params;
    params.add_input(input);
    params.add_output(output);
    params.add_inout(scratch);
    params.add_scalar(orch_args.scalar(0));
    params.add_scalar(orch_args.scalar(1));
    rt_submit_aiv_task(0, params);
}}

}}  // extern "C"
"""

# ---------------------------------------------------------------------------
# Kernel config for runtime assemble
# ---------------------------------------------------------------------------

def _kernel_config_py(task_name: str, count: int) -> str:
    return f"""\
# Auto-generated allreduce kernel config.
# Generated by PyPTO distributed codegen (allreduce_builtin.py).

from pathlib import Path

_ROOT_DIR = Path(__file__).parent

RUNTIME_CONFIG = {{
    "runtime": "tensormap_and_ringbuffer",
    "aicpu_thread_num": 4,
    "block_dim": 24,
}}

ORCHESTRATION = {{
    "source": str(_ROOT_DIR / "orchestration" / "{task_name}.cpp"),
    "function_name": "allreduce_orchestration",
    "signature": ["in", "out", "inout"],
}}

KERNELS = [
    {{
        "func_id": 0,
        "name": "allreduce_kernel",
        "source": str(_ROOT_DIR / "kernels" / "aiv" / "allreduce_kernel.cpp"),
        "core_type": "aiv",
        "signature": ["in", "out", "inout"],
    }},
]
"""

# ---------------------------------------------------------------------------
# Comm manifest entry for scratch buffer
# ---------------------------------------------------------------------------

def _comm_manifest_scratch_spec(count: int) -> dict[str, Any]:
    nbytes = max(count * 4 + 16 * 4, 4 * 1024)  # count*float32 + signal_tail, 4KB min
    return {
        "name": "scratch",
        "nbytes": int(nbytes),
        "load_from_host": False,
        "store_to_host": False,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def emit_allreduce_chip_task(
    output_dir: str,
    *,
    count: int = ALLREDUCE_COUNT,
    max_ranks: int = 16,
    task_name: str = "allreduce_kernel",
) -> dict[str, str]:
    """Emit a self-contained allreduce chip task bundle.

    Produces files under ``next_levels/{task_name}/``:
      - ``kernels/aiv/allreduce_kernel.cpp`` — 4-phase PTO-ISA kernel
      - ``orchestration/{task_name}.cpp`` — arg-forwarding orchestration shim
      - ``kernel_config.py`` — runtime compile config

    The caller is responsible for also emitting a ``CommGroup`` with a
    ``WindowBuffer(name="scratch", size=nbytes)`` to the comm manifest.

    Args:
        output_dir: Base output directory (e.g., ``/tmp/build_output/...``).
        count: Number of float32 elements to allreduce.
        max_ranks: Maximum supported rank count (must match ``ChipCommBootstrapConfig.nranks``).
        task_name: Directory name under ``next_levels/``.

    Returns:
        Dict of ``{relative_path: content}`` suitable for merging into
        ``result_files`` in ``pto_backend._generate_with_distributed()``.
    """
    kernel_cpp = _ALLREDUCE_KERNEL_CPP.format(
        ALLREDUCE_COUNT=count,
        MAX_RANKS=max_ranks,
    )
    orch_cpp = _ALLREDUCE_ORCH_CPP
    config_py = _kernel_config_py(task_name, count)

    base = f"next_levels/{task_name}"
    return {
        f"{base}/kernels/aiv/allreduce_kernel.cpp": kernel_cpp,
        f"{base}/orchestration/{task_name}.cpp": orch_cpp,
        f"{base}/kernel_config.py": config_py,
    }


__all__ = [
    "ALLREDUCE_COUNT",
    "SCRATCH_NBYTES",
    "emit_allreduce_chip_task",
    "_comm_manifest_scratch_spec",
]
